version: "3"

services:
  postgis:
    image: mdillon/postgis
    ports:
      - '5432:5432'

  data-prep:
    build: .
    volumes:
      - .:/data
    command: /data/prep/get-data.sh
    depends_on:
      - postgis
